name: HexiAwards
main: com.hexicraft.awards.Main
version: 1.0
description: Assists host with presenting the HexiAwards.
commands:
  award:
    description: The main command
    usage: /awards
    permission: hexiawards.admin
    permission-message: You don't have permission to do this.
    aliases: [awards,ha]